### ISSUE TITLE
Umbrella taks

### ISSUE THREAD

**Issue by kasparvonbeelen** [kasparvonbeelen/training-20190328#5]
- [x] The first task (#1)
- [x] The second task (#4)
- [ ] The last task (#3)
